:Author: jlutzwpi
:Email: justin.e.lutz@gmail.com
:Date: 07/03/2022
:Revision: version#1
:License: Public Domain

= Project: {Project}

Describe your project

Use an Edge Impulse advanced anomaly detection model to determine if a heat pump is off or on.
In addition, determine if the heat pump fan is operating appropriately.  If it's vibrating too much,
the dashboard will indicate an issue, and red LEDs will illuminate at the Opla base.

== Step 1: Installation
Load Heat_Pump_mar07a.ino sketch to the MKR Wifi 1010.  Note: requires the Edge Impulse Arduino
library to be loaded.

== Step 2: Assemble the circuit

No assembly outside of what it takes to put together an Opla.

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Heat_Pump_mar07a                => Arduino sketch folder
  ├── Heat_Pump_mar07a.ino       => main Arduino file
  └── ReadMe.adoc                => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: justin.e.lutz@gmail.com

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name              | Part number | Quantity
|    | Arduino Opla IOT kit   | AKX00026    | 1       
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
