// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


float anomaly_val;
bool no_issues;
bool state;

void initProperties(){

  ArduinoCloud.addProperty(anomaly_val, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(no_issues, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(state, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
